### ISSUE TITLE
请问博主，训练模型时是等它准确率到1后自动停止还是随时停止模型即保持当前准确度？

### ISSUE THREAD

**Issue by tigerwang1** [ZhengJun-AI/CarPlateIdentity#1]

**Comment by ZhengJun-AI** [comment]
最好的做法是划分验证集，在训练过程中选取验证集准确率最高的结果保存。

**Comment by tigerwang1** [comment]
> 最好的做法是划分验证集，在训练过程中选取验证集准确率最高的结果保存。

其实是字符训练了三个小时准确率到0.9了还没停有点急了QAQ顺带想请问下博主，最终实验大概能达到多少的准确率

**Comment by ZhengJun-AI** [comment]
你好，邮件已收到！——学委 郑均

**Comment by ZhengJun-AI** [comment]
时间隔得太久远了  有点忘了
其实按照我现在的眼光来看，当初采用的这个分类模型太简单了，而且没有进行合理地数据增广，因此训练得出的模型应该不会太好，你要是有兴趣交流的话可以留个qq

**Comment by tigerwang1** [comment]
> 时间隔得太久远了 有点忘了 其实按照我现在的眼光来看，当初采用的这个分类模型太简单了，而且没有进行合理地数据增广，因此训练得出的模型应该不会太好，你要是有兴趣交流的话可以留个qq

可以啊，2117765731大佬带我
